import React from 'react';
import {
    Home,
    Users,
    Layers,
    Briefcase,
    CheckSquare,
    Info,
    Clipboard,
    MessageSquare,
    Activity,
    AlertTriangle,
    BarChart2,
    Database,
    MessageCircle,
    Globe,
    Shield,
    FileText,
    Settings,
    FilePlus,
    Clock,
    Wrench,
    Printer,
    Edit3,
    ArrowRightLeft,
    RotateCcw,
    Archive,
    Search,
    AlertCircle,
    Star,
    Megaphone,
} from 'lucide-react';

const iconMap = {
    home: Home,
    users: Users,
    layers: Layers,
    briefcase: Briefcase,
    'check-square': CheckSquare,
    info: Info,
    clipboard: Clipboard,
    'message-square': MessageSquare,
    activity: Activity,
    'alert-triangle': AlertTriangle,
    'bar-chart-2': BarChart2,
    database: Database,
    'message-circle': MessageCircle,
    globe: Globe,
    shield: Shield,
    'file-text': FileText,
    settings: Settings,
    'file-plus': FilePlus,
    clock: Clock,
    tool: Wrench,
    printer: Printer,
    edit: Edit3,
    shuffle: ArrowRightLeft,
    repeat: RotateCcw,
    archive: Archive,
    search: Search,
    'alert-circle': AlertCircle,
    star: Star,
    megaphone: Megaphone,
};

export default function MenuIcon({ name, className = 'w-5 h-5' }) {
    const IconComponent = iconMap[name] || FileText;
    return <IconComponent className={className} />;
}
